- name: Install pm2
  npm:
    name: pm2
    version: "{{ pm2_version }}"
    global: true

- name: Create pm2 group
  group:
    name: "{{ pm2_group }}"

- name: Create pm2 user
  user:
    name: "{{ pm2_user }}"
    group: "{{ pm2_group }}"
    home: "{{ pm2_home }}"
    shell: /bin/false

- name: Add systemd config file
  template:
    src: etc/systemd/pm2.service.j2
    dest: /usr/lib/systemd/system/pm2.service
    owner: root
    group: root
    mode: 0644

- name: Enable and Start pm2 service
  systemd:
    name: pm2
    state: started
    enabled: true
    daemon_reload: true