- name: Install pm2
  npm:
    name: pm2
    global: true

- name: Create pm2 group
  group:
    name: pm2

- name: Create pm2 user
  user:
    name: pm2
    group: pm2
    home: /var/lib/pm2
    shell: /bin/false

- name: Add systemd config file
  template:
    src: etc/systemd/pm2.service.j2
    dest: /usr/lib/systemd/system/pm2.service
    owner: root
    group: root
    mode: 0644

- name: Start pm2 service
  systemd:
    name: pm2
    state: started
    enabled: true
    daemon_reload: true